table_edit_ConditionsTab=//*[@class='sbi-dom-table-info-title text-center']//span[text()='Conditions']
condition_operator = //div[@class='sbi-g-kendo-list-row justify-content-between']//kendo-dropdownlist[1]
condition_value_input = (//label[text()='Condition Type']/following::input)[2]
table_filter_saveBtn = //div[contains(@class,'sbi-dom-tab-footer d-flex align-items-center')]//*[text()='Save']
Conditions_OptionalFiltdropdown_list=//*[@class="k-list-ul"]//li
Conditions_dropdown=//kendo-dropdownlist[contains(@class,'sbi-g-kendo-dropdown sbi-g-kendo-list-row-drop-down sbi-dm-dropdown')]/span
table_conditionDRopArea=//app-table-conditions//div[@cdkdroplist]
tableEdit_columns_search=//app-columns//kendo-textbox//input
table_columns_in_columns_tab=//div[@class='ag-selection-checkbox']//following-sibling::span//div[@class='row sbi-column-style g-0 ng-star-inserted']
edit_table_columns_in_columns_tab=//div[@class='sbi-ag-grid-icons text-end']//span[@ng-reflect-message='Edit']
columnMoreIcon_in_columns_tab=//div[@class='sbi-ag-grid-icons text-end']//span[@ng-reflect-message='More']
Domain_Table_ListOfValues_drpdwn=(//*[@formcontrolname='listOfValuesOptions'])/child::span
save_in_column_edit=//button[@aria-label='Save']
columnMoreDelete_in_ColumnsTab=//li[@class='sbi-dm-table-action-menu-item ng-star-inserted']//span[text()='Delete']
columnMoreDelete_Popup_ColumnsTab=//button[text()='Continue']
tableColumnsTab_SyncWithDatabaseButton=//span[text()='Sync with Database']
tableColumnsTab_Save=//div[@class='sbi-dm-paging-btns']//button[text()='Save' and @class='sbi-btn sbi-primary-btn']
tableColumn_aggregationDropDown=(//*[@formcontrolname='columnAggregation'])/child::span
tableColumn_NumberFormatDropDown=(//*[@formcontrolname='numberFormat'])/child::span
CurrencyField_ColumnEdit=//input[@formcontrolname='currency']
DecimalPlaceField_ColumnEdit=//input[@formcontrolname='numberOfDecimals']
table_edit_UsageTab=//*[@class='sbi-dom-table-info-title text-center']//span[text()='Table Usage']
SQLtable_QueryFieldValidation=//*[text()=' SQL Query is required ']
SQLtable_ConenctionValidation=//*[text()=' Connection Name is required ']
SQL_executeQuery_WithDataButton= //button[text()=' Execute query with Data ']
SQL_executeQuery_WithOutDataButton= //button[text()=' Execute query without Data ']
SQL_Invalidquery_Validation=//*[contains(text(), 'ORA-00936: missing expression')]

//tableshare
table_moreOption_Share=//li[@class='sbi-dm-table-action-menu-item ng-star-inserted']//span[text()='Share']
TableShare_UserGroupTab=//span[text()=' User Group ']
TableShare_UsersTab=//span[text()=' User ']
SecurityRadioBtn_sharedUserOrUsergroup = //label[text()='Shared Users/Usergroups']//preceding-sibling::input
UserOrUsergroupAddIcon=//li[@title='Add']//span
SearchIn_UsersOrUsergroupsTab=//*[contains(@class,'sbi-share-search ps-1 k-textbox k-input')]//input
selectAll_UsersTab=(//*[@col-id='userName' and @role='columnheader'])[2]//child::span//input
selectAll_UserGroupsTab=(//*[@col-id='userGroupName' and @role='columnheader'])[2]//child::span//input
AddButton_InAvailableUsersOrUsergroups=//*[@title='Add' and text()='Add']
ShareButton_InUsersOrUserGroupsTab=//*[@title='Share' and text()='Share']
TableShare_EditCheckbox=//input[@title='editEnabled']
TableShare_ShareCheckbox=//input[@title='shareEnabled']
TableShare_ExportCheckbox=//input[@title='exportEnabled']
TableShare_CopyCheckbox=//input[@title='copyEnabled']
TableShare_DeleteCheckbox=//input[@title='deleteEnabled']

tableMore_export=//li[@class='sbi-dm-table-action-menu-item ng-star-inserted']//span[text()='Export']
tableMore_delete=//li[@class='sbi-dm-table-action-menu-item ng-star-inserted']//span[text()='Delete']
table_delete_PopupContinue=//button[@class='sbi-btn sbi-primary-btn'and text()='Continue']
tableMore_copy=//li[@class='sbi-dm-table-action-menu-item ng-star-inserted']//span[text()='Copy']
table_edit_JoinsTab=//*[@class='sbi-dom-table-info-title text-center']//span[text()='Joins']
domains_tree_view = //kendo-treeview[@textfield='domainName']//li//span[@draggable='true']
joins_tab_grid_view = //span[text()='Drag and Drop Table(s) to create Join']
reverse_join = //div[@class='sbi-g-kendo-list-row']//span[contains(@class,'form-switch sbi-toggle-btn-sm')]/input
searchDomain_OrTable_JoinsTab = //*[@placeholder='Search Domain / Table']
joinsTab_DomainExpand=//app-joins-domains//kendo-svgicon[@class='k-svg-i-caret-alt-right k-svg-icon k-icon ng-star-inserted' and @aria-hidden='true']

table_Save_JoinsTab=//button[@aria-label='save joins']
table_edit_SettingsTab=//*[@class='sbi-dom-table-info-title text-center']//span[text()='Settings']
table_edit_SettingsAllowDefaultSelfLOV=//*[@ng-reflect-name='ALLOW_DEFAULT_SELF_LOV_L']
table_edit_settings_Save=//div[contains(@class,'sbi-dm-settings-tab-footer d-flex align-items')]//button[text()='Save' and @class='sbi-save sbi-btn sbi-primary-btn']

tableMore_copy_disable=//li[@class='sbi-dm-table-action-menu-item ng-star-inserted']//a[contains(@class,'disable')]//span[text()='Copy']