business_application_list=//span[contains(@class,'sbit-ad-ba-name-edit')]
search_in_folders = input[title='Search']
folders_list = //div[@class='sbi-ad-grid-icon-circle sbit-ad-grid-icon-circle']/following-sibling::span
arrow_icon_for_sub_folder=//span[@class='ag-icon ag-icon-tree-closed']
business_applications=//*[@aria-label="Business Applications Image"]
expand_Icon_SubFolder=//*[@aria-label="Options list"]//kendo-treeview//ul//kendo-svgicon