search_in_workspace = //*[@id="workspace"]//*[@aria-label="Workspace search aria"]//input
searched_item=//div[contains(@class,'sbi-workspace-object-name-icon')]//span[text()='%s']
tabClose=//span[contains(@class,'tab-close sbi-new-icon')]
close_info=//span[@aria-label='Close Info']
refresh_icon=//button[contains(@data-title,'Refresh (ctrl + alt + r)')]