# Root logger option
log4j.rootLogger= INFO, console, FILE

# Direct log messages to a log file
log4j.appender.console=org.apache.log4j.ConsoleAppender
#log4j.appender.console.Threshold=DEBUG
#log4j.appender.console.Target=System.out
log4j.appender.console.layout=org.apache.log4j.SimpleLayout
log4j.appender.FILE=org.apache.log4j.FileAppender
log4j.appender.FILE.File=consoleLogs.log
log4j.appender.FILE.layout=org.apache.log4j.SimpleLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L ? %m%n

