create_user=button[title='Create']
admin_create_user_username = //*[@formcontrolname='userName']
admin_create_user_firstname = //*[@formcontrolname='firstName']
admin_create_user_lastname = //*[@formcontrolname='lastName']
admin_create_user_email = //*[@formcontrolname='emailAddress']
let_me_create_pwd = #mat-radio-4-input
admin_create_user_password =//input[@value='create_password']
admin_enter_password=//input[@title='User Password']
save_and_next=button[aria-label='Save and Next Button']
Save_button=//button[@aria-label='Save Button']
Select_button=//button[text()='Select']
click_OK=//button[@title='OK']
#Create User - Access & Roles
admin_developer_access_toggle=//*[@id="sbi-ad-user-enable-DEVELOPER"]
ReadOnly_Tap=//input[@id='sbi-ad-user-enable-READ_ONLY']
admin_checkbox=//input[@name="adminAccess"]
developer_Uncheck=//*[@name="developerAccess"]
Exclude_permission=//span[@class='sbi-link-with-underline']
Domains_ExcludePermission=//*[text()='Domains']//following-sibling::div[@col-id="excludePermissions"]
tenent_admin_checkbox=//*[@ng-reflect-name="tenantAdminAccess"]
#Connectors_Tab=//span[@class='sbi-left-menu-text sbit-left-menu-text text-truncate'][normalize-space()='Connections']
create_domain_checkBox = //mat-checkbox//*[text()='Create Domain']
Add_Usergroup=//button[@aria-label=' Add ' or text()='Add User Groups ']
SearchIn_AvailableUserGroup=//*[contains(@class,'sbi-g-search sbi-grid-list-search-input k-textbox k-input')]//input
selectButton_AvaialbleUserGroup=//button[@class='sbi-btn sbi-primary-btn' and text()='Select']
selectAllCheckBox_AvailableUserGroup=//*[@class="ag-labeled ag-label-align-right ag-checkbox ag-input-field ag-header-select-all"]
selectCheckbox_AvailableUserGroup=//input[@aria-label='Press Space to toggle row selection (unchecked)']
#Create User - Settings
admin_create_user_share_reports = //input[contains(@id,'sbi-enable-customize-option-Share Reports')]

#Connectors
Connectors_Tab=//span[@class='sbi-left-menu-text sbit-left-menu-text text-truncate'][normalize-space()='Connections']
Connector=//*[@aria-label="Connections"]
search_inputbox=//input[@placeholder='Search']//input
connector_SearchBox=//input[@title='Search']
More_connector=//*[@aria-label="More"]
Share_Connector=//li[normalize-space()='Share']
Share_Add_User=//*[@aria-label="Add User"]
select_first_check_box= //div[@col-id='userName' and @role='gridcell']//input
Available_User_SearchBox=//kendo-textbox[contains(@class,'sbi-share-search ps-1')]//input
Add_Available_User=//button[normalize-space()='Add']
Connector_Share_Btn=//*[@aria-label=" Share"]
delete = //li[@role='menuitem' and @title='Delete']
select_all_checkboxes=//div[contains(@class,'sbi-g-share-container')]//input[contains(@class,'k-checkbox')]
delete_confirmation_button = //*[contains(@class,'sbi-primary-btn') and text()='OK']
profile_icon=//*[@aria-label='Profile' and @title='Profile']
logout_button=//span[normalize-space()='Logout']
login_username=//input[@id='floatingInput']
login_password=//input[@id='floatingPassword']
Sign_In=//button[@type='submit']
Create_password=//input[contains(@class,'mat-mdc-input-element sbi-change-password-input')]
Confirm_Password=//input[@formcontrolname='confirmNewPassword']
Reset_Submit=//button[@type='submit']
SUCCESS_MESSAGE=//span[text()='Your Password has been reset successfully.']
password_must_text=//span[text()='Password must contain 8 Characters']
Login_Btn=//button[normalize-space()='LOGIN']
ResetPasswordTXT=//h3[normalize-space()='Reset Password']
setUp=//*[text()=" Setup "]



