#create Report
report_name = //*[@formcontrolname='reportName']
search_DomainName = //kendo-textbox[contains(@class,'sbi-g-search k-textbox k-input k-input') and @ng-reflect-placeholder='Search']//input
searched_domainName = //span[@class='sbi-business-app-name text-truncate']
select_domainName=//table[contains(@class,'k-grid-table k-table')]
reports_list_container = //kendo-splitter-pane//div[contains(@class,'sbi-re-tables-right-content')]
tableColumns_InReport=//span[@class='sbi-tree-col-name' and @ng-reflect-position='right']
report_save = //li[@aria-label='Save Report']
Report_Name_field=//input[@formcontrolname='reportName']
Save_report_Btn=//button[@class='sbi-btn-sm sbi-btn sbi-primary-btn sbi-btn-highlight sbit-save-modal']
save_publish = //button[contains(@class,'sbi-save-rep-dd sbi-no-border-no-bg-btn ng-star-inserted')]
Publish=//li[@class='sbi-g-dropdown-item d-flex sbit-publish-report']
publishAndRun_InReport=//li[@title='Publish & Run (R + P)']
more_btn = //div[contains(@class,'sbi-grid-action-list sbit-grid-action-list')]//button[contains(@class,'mat-mdc-menu-trigger mat-mdc-tooltip-trigger sbi-new-icon')]
table_column_names=//span[text()='%s']/ancestor::span[2]
domain_list_in_rep_create=//h6[contains(@aria-label, 'Domain Name : %s')]
report_dilldownIcon=//div[@ng-reflect-message='Drill Down (R + L)']/span
drill_createIcon = //button[@aria-label='Create Drill']
drilldown_columnsDropdown = //label[text()='Drilldown Columns']/following-sibling::kendo-dropdownlist
Drill_DrillSet_SelectIcon=//button[@title='Select Rpeort or Drill Table']
Drill_set_Name_radio_btn=//*[@class="radio-container"]//input
Drill_DrillSet_SelectPage_OK=//button[@aria-label='select drill or report']
DrillPage_Mapping=//button[@aria-label='Mapping']
drill_report_column_search = //div[@aria-label='Report Column or Filter Column']//button[1]
drill_column_Filter_search = (//button[@aria-label='Report Column or Filter FX Popup'])[2]
Drill_report_columns = //div[contains(@class,'sbi-reports-column-list-item')]//span[2]
drill_filter_columns = //*[@class="k-listview-content"]//div[@class="k-listview-item ng-star-inserted"]
drill_column_formulaField=//textarea[@ng-reflect-name='formula']
drill_ReportCol_FilterCol_save=//button[text()=' Save ' and @class='sbi-btn-sm sbi-btn sbi-primary-btn sbi-btn-highlight sbit-on-save']
drill_pageSave=//button[@class='sbi-btn sbi-primary-btn sbi-drill-save-btn']
drillOrDrillSet_nameSearch=//*[@class='sbi-g-search k-textbox k-input k-input-md k-rounded-md k-input-solid']//input
report_ConditionsIcon=//div[@ng-reflect-message='Conditions (R + C)']/span
report_ConditionsList=//div[@class='cdk-drag sbi-g-listview-content-row sbi-re-columns-list-row ng-star-inserted']//span
conditions_tab_ColumnDropArea = //ul[contains(@class,'cdk-drop-list sbi-g-listview-content')]
report_FiltersIcon=//div[@ng-reflect-message='Filters (R + F)']/span
filters_tab_ColumnDropArea=//ul[contains(@class,'cdk-drop-list sbi-re-filters-list-view sbit-re-filters')]
filters_ListOfValuesTab=//div[@class='sbi-g-tab-title ng-star-inserted' and text()=' List of Values ']
filters_ListOfValuesSource=//*[@aria-label='List of Values Source']//child::kendo-dropdownlist//span[@class='ng-star-inserted']
table_expand = //*[text()='%s']//preceding::kendo-svgicon[1]
Expand_All=//span[@class='mat-mdc-tooltip-trigger sbi-new-icon-390 sbi-tree-view-maximize-icon p-2 sbi-g-icon ng-star-inserted']
reports_grid_view = (//kendo-splitter-pane//div[@class='ag-center-cols-viewport' and @ref='centerContainer'])[3]
report_datagrid_previeDataDropdown=//kendo-dropdownlist[contains(@class,'sbi-data-grid-preview-dd k-picker-md')]//span[@class='k-input-inner']
report_datagrid_DataFirstRow=(//div[contains(@class,'ag-cell-value ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-column-first ag-column')])[1]
//submit
report_submit=//button[text()='Submit']
past_submissions_refresh =//span[@class='sbi-new-icon-118 sbi-re-refresh-btn-icon']
hover_Submitted_Report=//div[contains(@class,'ag-row-even ag-row-not-inline-editing')]//div[@class="ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-column-first ag-cell-focus"]
submission_status =//*[@class='ag-cell-value ag-cell ag-cell-not-inline-editing ag-cell-normal-height']//span[@class='sbi-g-cp ng-star-inserted']
report_submission_status = (//*[@role='gridcell' and @col-id='status']//span)[1]
Report_Output_Icon_1=(//div[@col-id='outputs']//app-sbi-selection-list-template-render)[1]
HTMLoutput=//a[@routerlink='/htmloutput']/span
html_tab_header = //div[@class='sbi-title-logo']//div
html_window_ViewSql=//button[@class='sbi-btn sbi-light-btn sbi-view-sql-btn ng-star-inserted' and text()=' View SQL']