#Updating test data file executed on instance: http://192.168.4.117/#/
#Tue Mar 11 13:19:16 IST 2025
ConnectorUserName=Automation_User_smjyx4
EbsDomain=Automation_Ebs__glfrkk
EbsSqlDomain=EbsSqlAutoDomain_rc68z8
NonEbsDomain=Automation_NonEbs__umz56a
NonEbsSqlAutoDomainColProp=NonEbsSqlAutoDomainColProp_zjq94l
NonEbsSqlAutoDomaindrill=NonEbsSqlAutoDomaindrill_gc4957
NonEbsSqlDomain=SqlAutoDomainSelfLOVsetting_wapk1q
NonEbsSqlDomainShareUG=NonEbsSqlDomainShareUG_kg000j
OCCSqlDomain=OCCSqlAutoDomain_haf359
SqlAutoDomainTableCond=SqlAutoDomainTableCond_zy6cg3
UserName1=Automation_User_76uv1n
