domain_name_in_details = (//*[contains(@class,'sbit-domain-name')]//*[@formcontrolname="domainName"]//input)[3]
domain_code_in_details =  (//*[contains(@class,'sbit-domain-code')]//*[@formcontrolname="domainCode"]//input)[3]
business_app_dropdown = (//kendo-dropdownlist[@textfield='name']/span)[3]
dropdown_list_values = //kendo-popup//kendo-list//li
folders_dropdown=//kendo-dropdowntree[@childrenfield='folders']
folders_dropdown_list_values = //kendo-popup//kendo-treeview/ul/li
folder_name_input_for_new=input#folderName
folder_save_icon=//div[contains(@class,'sbi-create-folder sbi-form-row')]//button[2]
close_btn=//app-create-edit-domain[@ng-reflect-domain-handler='[object Object]']//div//div/div[3]/button[1]
default_db_conn_dropdown = (//kendo-dropdownlist[@aria-label='Default Database Connection']/span)[3]
default_db_conn_dropdown_text=(//kendo-dropdownlist[@aria-label='Default Database Connection']/span/span)[3]
business_app_dropdown_text =(//kendo-dropdownlist[@textfield='name']/span/span)[3]
createDomain_close=//app-create-edit-domain[@class='ng-star-inserted']//button[@aria-label='Close']
